### ISSUE TITLE
Wrong upload url in oshpark-upload.ulp

### ISSUE THREAD

**Issue by CaptIgmu** [OSHPark/OSHPark-Eagle-Tools#1]
instead of this: string OSHPARKURL="http://oshpark.com/import.eagle_import";
should be the secure site: string OSHPARKURL="https://oshpark.com/import.eagle_import";
Every time you UPDATE your OSH Park tools in Eagle, the wrong url will be installed!

**Comment by tekdemo** [comment]
Fixed! It'll redirect internally, so this shouldn't be an actual problem, but HTTPS is always better. 
https://github.com/OSHPark/OSHPark-Eagle-Tools/commit/22c824dd50e055af728a45ec6983170da21c7ce4

**Comment by tekdemo** [comment]
This was totally an issue. Apparently the redirect didn't actually work how I was expecting, so this did cause failed uploads. Thanks a ton for the tip so I could fix this!
